version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run tests and generate report
          command: |
            mkdir -p reports
            pytest -s --junitxml=reports/report.xml

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports

workflows:
  version: 2
  test-workflow:
    jobs:
      - test